[package]
name = "api"
version = "0.1.0"
authors = ["Florian Warzecha <liketechnik@disroot.org>"]
edition = "2018"

[dependencies]
gotham = "0.4.0"
gotham_derive = "0.4.0"
serde = "1.0.104"
serde_json = "1.0.46"
hyper = "0.12"
mime = "0.3"

shared = { path = "../shared" }

